TRUNCATE TABLE devices RESTART IDENTITY CASCADE;

TRUNCATE TABLE users RESTART IDENTITY CASCADE;

TRUNCATE TABLE sessions RESTART IDENTITY CASCADE;

TRUNCATE TABLE pulse_measurements RESTART IDENTITY CASCADE;

ALTER TABLE sessions
    ADD COLUMN session_status VARCHAR NOT NULL DEFAULT 'Open';