---
networks:
  pulsometer_network:
    driver: bridge
services:
  hivemq:
    container_name: pulsometer_hivemq
    image: hivemq/hivemq-ce
    ports:
      - 1883:1883
      - 1884:8080
    networks:
      - pulsometer_network
    restart: unless-stopped
  backend:
    container_name: pulsometer_backend
    image: hlofiys/pulsometer-backend:master
    ports:
      - 8081:8081
    networks:
      - pulsometer_network
    depends_on:
      - hivemq
      - pulsometer_db
    restart: unless-stopped
  frontend:
    container_name: pulsometer_frontend
    image: hlofiys/pulsometer-frontend:master
    ports:
      - 8080:80
    networks:
      - pulsometer_network
    depends_on:
      - backend
    restart: unless-stopped
  pulsometer_db:
    container_name: pulsometer_db
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - pulsometer_network
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
