---
networks:
  pulsometer_network:
    driver: bridge
services:
  hivemq:
    image: hivemq/hivemq-ce
    ports:
      - 1883:1883
    networks:
      - pulsometer_network
    restart: unless-stopped
  backend:
    image: gitea.hlofiys.xyz/hlofiys/pulsometer-backend:master
    ports:
      - 8080:8080
    networks:
      - pulsometer_network
    depends_on:
      - hivemq
      - db
    restart: unless-stopped
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - pulsometer_network
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:  
    